# Site settings
title: Helloted Blog
header-img: img/home-bg.jpg
email: helloted@live.com
copyright_name: Helloted
description: "曹浩之Helloted的技术博客，用于记录一些技术成长过程中的技术分享，包括客户端iOS/Android，后台Pyhon/Java，跨平台开发Flutter"
baseurl: ""
url: "http://www.helloted.com"

github_username: helloted
email_username: helloted@live.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
paginate: 25
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

plugins: [jekyll-paginate, jekyll-feed]
