# Site settings
title: Helloted Blog
header-img: img/home-bg.jpg
email: helloted@live.com
copyright_name: Helloted
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://www.helloted.com"



github_username:  helloted
email_username:  helloted@live.com
zhihu_username:  大写的程序员

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
